### ISSUE TITLE
Allow defaults for HashOptions

### ISSUE THREAD

**Issue by garysb** [fdionisi/deno-argon2#2]
Please allow us to not have to specify all options. I would like to provide a salt without having to specify everything. The other options should revert to the defaults.

**Comment by fdionisi** [comment]
You already can. The [hash function](https://github.com/fdionisi/deno-argon2/blob/master/lib/internal.ts#L53-L55) takes a `Partial<HashOptions>` as optional parameter. Regarding the Rust part are defined but following the default of the underlying library.

**Comment by garysb** [comment]
I receive the following:
```
Type '{ salt: Uint8Array; }' is missing the following properties from type 'HashOptions<{}>': secret, data, variant, version, and 5 more.ts(2740)
```

with the code:
```
const hashOptions: HashOptions = { salt: account.salt };
```

**Comment by garysb** [comment]
Ah, got it sorted, thanks for leading me in the right direction.
